# Generated by Django 2.1.5 on 2019-12-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191030_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='', verbose_name='ファイル'),
        ),
    ]
